# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MataElangManagement.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

import os
import sys
import subprocess
import docker
import shutil
import sqlite3
from os.path import abspath, dirname

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QInputDialog
from PyQt5.QtSql import QSqlDatabase, QSqlQuery
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1440, 1024)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidebarFrame = QtWidgets.QFrame(self.centralwidget)
        self.sidebarFrame.setGeometry(QtCore.QRect(0, 0, 291, 971))
        self.sidebarFrame.setStyleSheet("background-color: rgb(44, 62, 80);")
        self.sidebarFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidebarFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidebarFrame.setObjectName("sidebarFrame")
        self.layoutWidget = QtWidgets.QWidget(self.sidebarFrame)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 130, 261, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.sidebarLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.sidebarLayout.setContentsMargins(0, 0, 0, 0)
        self.sidebarLayout.setObjectName("sidebarLayout")
        self.dashboardButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.dashboardButton.setFont(font)
        self.dashboardButton.setStyleSheet("color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icon/dashboard-24.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dashboardButton.setIcon(icon)
        self.dashboardButton.setIconSize(QtCore.QSize(22, 22))
        self.dashboardButton.setAutoDefault(False)
        self.dashboardButton.setDefault(False)
        self.dashboardButton.setFlat(True)
        self.dashboardButton.setObjectName("dashboardButton")
        self.dashboardButton.clicked.connect(lambda : self.stackedWidget.setCurrentIndex(0))
        self.sidebarLayout.addWidget(self.dashboardButton)
        self.monitoringButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.monitoringButton.setFont(font)
        self.monitoringButton.setStyleSheet("color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icon/email-12-24.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.monitoringButton.setIcon(icon1)
        self.monitoringButton.setIconSize(QtCore.QSize(22, 22))
        self.monitoringButton.setFlat(True)
        self.monitoringButton.setObjectName("monitoringButton")
        self.monitoringButton.clicked.connect(lambda : self.stackedWidget.setCurrentIndex(1))
        self.sidebarLayout.addWidget(self.monitoringButton)
        self.layoutWidget1 = QtWidgets.QWidget(self.sidebarFrame)
        self.layoutWidget1.setGeometry(QtCore.QRect(100, 10, 180, 111))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.profileLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.profileLayout.setContentsMargins(0, 0, 0, 0)
        self.profileLayout.setObjectName("profileLayout")
        self.profile2Layout = QtWidgets.QVBoxLayout()
        self.profile2Layout.setObjectName("profile2Layout")
        self.admin_label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.admin_label.setFont(font)
        self.admin_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.admin_label.setObjectName("admin_label")
        self.profile2Layout.addWidget(self.admin_label)
        self.menuprofileLayout = QtWidgets.QHBoxLayout()
        self.menuprofileLayout.setObjectName("menuprofileLayout")
        self.settingButton = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.settingButton.setFont(font)
        self.settingButton.setStyleSheet("color: rgb(255, 255, 255);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/icon/settings-5-24.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingButton.setIcon(icon2)
        self.settingButton.setIconSize(QtCore.QSize(16, 16))
        self.settingButton.setFlat(True)
        self.settingButton.setObjectName("settingButton")
        self.settingButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))
        self.menuprofileLayout.addWidget(self.settingButton)
        self.logoutButton = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setBold(True)
        font.setWeight(75)
        self.logoutButton.setFont(font)
        self.logoutButton.setStyleSheet("color: rgb(255, 255, 255);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/icon/logout-24.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logoutButton.setIcon(icon3)
        self.logoutButton.setFlat(True)
        self.logoutButton.setObjectName("logoutButton")
        self.menuprofileLayout.addWidget(self.logoutButton)
        self.profile2Layout.addLayout(self.menuprofileLayout)
        self.profileLayout.addLayout(self.profile2Layout)
        self.admin_photo = QtWidgets.QLabel(self.sidebarFrame)
        self.admin_photo.setGeometry(QtCore.QRect(20, 20, 71, 91))
        self.admin_photo.setText("")
        self.admin_photo.setPixmap(QtGui.QPixmap("assets/images/boss.png"))
        self.admin_photo.setScaledContents(True)
        self.admin_photo.setObjectName("admin_photo")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(300, 0, 1131, 971))
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboardPage = QtWidgets.QWidget()
        self.dashboardPage.setObjectName("dashboardPage")
        self.headerLabelDashboard = QtWidgets.QLabel(self.dashboardPage)
        self.headerLabelDashboard.setGeometry(QtCore.QRect(30, 40, 861, 61))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(36)
        self.headerLabelDashboard.setFont(font)
        self.headerLabelDashboard.setObjectName("headerLabelDashboard")
        self.tableHaderLabel = QtWidgets.QLabel(self.dashboardPage)
        self.tableHaderLabel.setGeometry(QtCore.QRect(30, 180, 161, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(24)
        self.tableHaderLabel.setFont(font)
        self.tableHaderLabel.setObjectName("tableHaderLabel")
        self.sensorListTable = QtWidgets.QTableWidget(self.dashboardPage)
        self.sensorListTable.setGeometry(QtCore.QRect(30, 250, 731, 251))
        self.sensorListTable.setObjectName("sensorListTable")
        self.sensorListTable.setColumnCount(6)
        self.sensorListTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.sensorListTable.setItem(4, 4, item)
        self.sensorListTable.horizontalHeader().setDefaultSectionSize(118)
        self.sensorListTable.verticalHeader().setDefaultSectionSize(44)

        # Tombol Menuju Halaman Add Sensor
        self.addSensorButton = QtWidgets.QPushButton(self.dashboardPage)
        self.addSensorButton.setGeometry(QtCore.QRect(30, 540, 121, 31))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.addSensorButton.setFont(font)
        self.addSensorButton.setAutoFillBackground(False)
        self.addSensorButton.setStyleSheet("background-color: rgb(52, 152, 219);\n"
"color: rgb(255, 255, 255);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("assets/icon/plus-24.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addSensorButton.setIcon(icon4)
        self.addSensorButton.setFlat(False)
        self.addSensorButton.setObjectName("addSensorButton")
        self.addSensorButton.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(2))
        


        self.stackedWidget.addWidget(self.dashboardPage)
        self.monitoringPage = QtWidgets.QWidget()
        self.monitoringPage.setObjectName("monitoringPage")
        self.headerLabelMonitorSensor = QtWidgets.QLabel(self.monitoringPage)
        self.headerLabelMonitorSensor.setGeometry(QtCore.QRect(30, 40, 301, 41))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(36)
        self.headerLabelMonitorSensor.setFont(font)
        self.headerLabelMonitorSensor.setObjectName("headerLabelMonitorSensor")
        self.tableHeaderMonitorSensor = QtWidgets.QLabel(self.monitoringPage)
        self.tableHeaderMonitorSensor.setGeometry(QtCore.QRect(30, 140, 141, 21))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(24)
        self.tableHeaderMonitorSensor.setFont(font)
        self.tableHeaderMonitorSensor.setObjectName("tableHeaderMonitorSensor")
        self.monitorSensorTable = QtWidgets.QTableWidget(self.monitoringPage)
        self.monitorSensorTable.setGeometry(QtCore.QRect(30, 190, 721, 261))
        self.monitorSensorTable.setObjectName("monitorSensorTable")
        self.monitorSensorTable.setColumnCount(7)
        self.monitorSensorTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(1, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(1, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(2, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(2, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(3, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(3, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(3, 6, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(4, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(4, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(4, 5, item)
        item = QtWidgets.QTableWidgetItem()
        self.monitorSensorTable.setItem(4, 6, item)
        self.monitorSensorTable.horizontalHeader().setDefaultSectionSize(116)
        self.monitorSensorTable.verticalHeader().setDefaultSectionSize(42)
        self.stackedWidget.addWidget(self.monitoringPage)

        # Halaman Add Sensor
        self.addSensorPage = QtWidgets.QWidget()
        self.addSensorPage.setObjectName("addSensorPage")
        self.headerLabelAddSensor = QtWidgets.QLabel(self.addSensorPage)
        self.headerLabelAddSensor.setGeometry(QtCore.QRect(30, 40, 221, 41))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(36)
        self.headerLabelAddSensor.setFont(font)
        self.headerLabelAddSensor.setObjectName("headerLabelAddSensor")
        self.layoutWidget2 = QtWidgets.QWidget(self.addSensorPage)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 130, 691, 461))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        # Field Protected Subnet
        self.protectedSubnetlabel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.protectedSubnetlabel.setFont(font)
        self.protectedSubnetlabel.setObjectName("protectedSubnetlabel")
        self.gridLayout.addWidget(self.protectedSubnetlabel, 0, 0, 1, 1)
        self.protectedSubnetlineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.protectedSubnetlineEdit.setObjectName("protectedSubnetlineEdit")
        self.gridLayout.addWidget(self.protectedSubnetlineEdit, 0, 1, 1, 2)
        

        # Field External Subnet
        self.externalSubnetLabel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.externalSubnetLabel.setFont(font)
        self.externalSubnetLabel.setObjectName("externalSubnetLabel")
        self.gridLayout.addWidget(self.externalSubnetLabel, 1, 0, 1, 1)
        self.externalSubnetlineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.externalSubnetlineEdit.setInputMask("")
        self.externalSubnetlineEdit.setObjectName("externalSubnetlineEdit")
        self.gridLayout.addWidget(self.externalSubnetlineEdit, 1, 1, 1, 2)
        

        # Field MQTT Topic
        self.mqttTopicLabel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.mqttTopicLabel.setFont(font)
        self.mqttTopicLabel.setObjectName("mqttTopicLabel")
        self.gridLayout.addWidget(self.mqttTopicLabel, 2, 0, 1, 1)
        self.mqttTopiclineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.mqttTopiclineEdit.setObjectName("mqttTopiclineEdit")
        self.gridLayout.addWidget(self.mqttTopiclineEdit, 2, 1, 1, 2)
        

        # Field MQTT IP
        self.mqttBrokerLabel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.mqttBrokerLabel.setFont(font)
        self.mqttBrokerLabel.setObjectName("mqttBrokerLabel")
        self.gridLayout.addWidget(self.mqttBrokerLabel, 3, 0, 1, 1)
        self.mqttBrokerIPlineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.mqttBrokerIPlineEdit.setObjectName("mqttBrokerIPlineEdit")
        self.gridLayout.addWidget(self.mqttBrokerIPlineEdit, 3, 1, 1, 2)
        

        # Field MQTT Port
        self.mqttBrokerPort = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.mqttBrokerPort.setFont(font)
        self.mqttBrokerPort.setObjectName("mqttBrokerPort")
        self.gridLayout.addWidget(self.mqttBrokerPort, 4, 0, 1, 1)
        self.mqttBrokerPortlineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.mqttBrokerPortlineEdit.setObjectName("mqttBrokerPortlineEdit")
        self.gridLayout.addWidget(self.mqttBrokerPortlineEdit, 4, 1, 1, 2)
        

        # Field Device ID
        self.deviceIDLabel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.deviceIDLabel.setFont(font)
        self.deviceIDLabel.setObjectName("deviceIDLabel")
        self.gridLayout.addWidget(self.deviceIDLabel, 5, 0, 1, 1)
        self.deviceIDlineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.deviceIDlineEdit.setObjectName("deviceIDlineEdit")
        self.gridLayout.addWidget(self.deviceIDlineEdit, 5, 1, 1, 2)
        

        # Field Device Name
        self.deviceNameLabel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.deviceNameLabel.setFont(font)
        self.deviceNameLabel.setObjectName("deviceNameLabel")
        self.gridLayout.addWidget(self.deviceNameLabel, 6, 0, 1, 1)
        self.deviceNamelineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.deviceNamelineEdit.setObjectName("deviceNamelineEdit")
        self.gridLayout.addWidget(self.deviceNamelineEdit, 6, 1, 1, 2)
        
        
        # Field Network Interface
        self.networkInterfaceLabel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.networkInterfaceLabel.setFont(font)
        self.networkInterfaceLabel.setObjectName("networkInterfaceLabel")
        self.gridLayout.addWidget(self.networkInterfaceLabel, 7, 0, 1, 1)
        self.networkInterfacelineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.networkInterfacelineEdit.setObjectName("networkInterfacelineEdit")
        self.gridLayout.addWidget(self.networkInterfacelineEdit, 7, 1, 1, 2)
        

        # Field Company
        self.companyLabel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.companyLabel.setFont(font)
        self.companyLabel.setObjectName("companyLabel")
        self.gridLayout.addWidget(self.companyLabel, 8, 0, 1, 1)
        self.companylineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.companylineEdit.setObjectName("companylineEdit")
        self.gridLayout.addWidget(self.companylineEdit, 8, 1, 1, 2)
        

        # Field Pilih Rule
        self.ruleChoiceLabel = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.ruleChoiceLabel.setFont(font)
        self.ruleChoiceLabel.setObjectName("ruleChoiceLabel")
        self.gridLayout.addWidget(self.ruleChoiceLabel, 10, 0, 1, 1)
        self.communityradioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.communityradioButton.setObjectName("communityradioButton")
        self.gridLayout.addWidget(self.communityradioButton, 10, 1, 1, 1)
        self.reisteredradioButton = QtWidgets.QRadioButton(self.layoutWidget2)
        self.reisteredradioButton.setObjectName("reisteredradioButton")
        self.gridLayout.addWidget(self.reisteredradioButton, 10, 2, 1, 1)

        # Tombol Buat Sensor
        self.createSensorButton = QtWidgets.QPushButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        self.createSensorButton.setFont(font)
        self.createSensorButton.setStyleSheet("background-color: rgb(52, 152, 219);\n"
"color: rgb(255, 255, 255);")
        self.createSensorButton.setObjectName("createSensorButton")
        self.createSensorButton.clicked.connect(self.createDataSensor)


        self.gridLayout.addWidget(self.createSensorButton, 11, 0, 1, 1)
        self.stackedWidget.addWidget(self.addSensorPage)
        self.settingPage = QtWidgets.QWidget()
        self.settingPage.setObjectName("settingPage")
        self.settingheaderLabel = QtWidgets.QLabel(self.settingPage)
        self.settingheaderLabel.setGeometry(QtCore.QRect(460, 50, 151, 41))
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(36)
        self.settingheaderLabel.setFont(font)
        self.settingheaderLabel.setObjectName("settingheaderLabel")
        self.layoutWidget3 = QtWidgets.QWidget(self.settingPage)
        self.layoutWidget3.setGeometry(QtCore.QRect(360, 280, 351, 221))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.nameSettingLabel = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.nameSettingLabel.setFont(font)
        self.nameSettingLabel.setObjectName("nameSettingLabel")
        self.gridLayout_2.addWidget(self.nameSettingLabel, 0, 0, 1, 1)
        self.nameSettinglineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.nameSettinglineEdit.setObjectName("nameSettinglineEdit")
        self.gridLayout_2.addWidget(self.nameSettinglineEdit, 0, 1, 1, 1)
        self.passwordSettingLabel = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(14)
        self.passwordSettingLabel.setFont(font)
        self.passwordSettingLabel.setObjectName("passwordSettingLabel")
        self.gridLayout_2.addWidget(self.passwordSettingLabel, 1, 0, 1, 1)
        self.passSettinglineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.passSettinglineEdit.setObjectName("passSettinglineEdit")
        self.gridLayout_2.addWidget(self.passSettinglineEdit, 1, 1, 1, 1)
        self.submitSettingButton = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setFamily("FontAwesome")
        font.setPointSize(12)
        self.submitSettingButton.setFont(font)
        self.submitSettingButton.setStyleSheet("background-color: rgb(52, 152, 219);")
        self.submitSettingButton.setObjectName("submitSettingButton")
        self.gridLayout_2.addWidget(self.submitSettingButton, 2, 0, 1, 2)
        self.stackedWidget.addWidget(self.settingPage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1440, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFind = QtWidgets.QMenu(self.menuEdit)
        self.menuFind.setObjectName("menuFind")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Window = QtWidgets.QAction(MainWindow)
        self.actionNew_Window.setObjectName("actionNew_Window")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionCUt = QtWidgets.QAction(MainWindow)
        self.actionCUt.setObjectName("actionCUt")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionFind_2 = QtWidgets.QAction(MainWindow)
        self.actionFind_2.setObjectName("actionFind_2")
        self.actionReplace = QtWidgets.QAction(MainWindow)
        self.actionReplace.setObjectName("actionReplace")
        self.menuFile.addAction(self.actionNew_Window)
        self.menuFile.addAction(self.actionExit)
        self.menuFind.addAction(self.actionFind_2)
        self.menuFind.addAction(self.actionReplace)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionCUt)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.menuFind.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dashboardButton.setText(_translate("MainWindow", "Dashboard"))
        self.monitoringButton.setText(_translate("MainWindow", "Monitoring"))
        self.admin_label.setText(_translate("MainWindow", "Admin"))
        self.settingButton.setText(_translate("MainWindow", "Setting"))
        self.logoutButton.setText(_translate("MainWindow", "Logout"))
        self.headerLabelDashboard.setText(_translate("MainWindow", "Welcome To Mata Elang Sensor Management "))
        self.tableHaderLabel.setText(_translate("MainWindow", "Sensor List"))
        item = self.sensorListTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.sensorListTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.sensorListTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.sensorListTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.sensorListTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.sensorListTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device ID"))
        item = self.sensorListTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Device Name"))
        item = self.sensorListTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Company"))
        item = self.sensorListTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location"))
        item = self.sensorListTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "IP"))
        item = self.sensorListTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Action"))
        __sortingEnabled = self.sensorListTable.isSortingEnabled()
        self.sensorListTable.setSortingEnabled(False)
        item = self.sensorListTable.item(0, 0)
        item.setText(_translate("MainWindow", "12021991"))
        item = self.sensorListTable.item(0, 1)
        item.setText(_translate("MainWindow", "sensor-pens-network-1"))
        item = self.sensorListTable.item(0, 2)
        item.setText(_translate("MainWindow", "PENS"))
        item = self.sensorListTable.item(0, 3)
        item.setText(_translate("MainWindow", "Surabaya, Jawa Timur, Indonesia"))
        item = self.sensorListTable.item(0, 4)
        item.setText(_translate("MainWindow", "192.168.1.0/24"))
        item = self.sensorListTable.item(1, 0)
        item.setText(_translate("MainWindow", "12021992"))
        item = self.sensorListTable.item(1, 1)
        item.setText(_translate("MainWindow", "sensor-pens-network-2"))
        item = self.sensorListTable.item(1, 2)
        item.setText(_translate("MainWindow", "PENS"))
        item = self.sensorListTable.item(1, 3)
        item.setText(_translate("MainWindow", "Surabaya, Jawa Timur, Indonesia"))
        item = self.sensorListTable.item(1, 4)
        item.setText(_translate("MainWindow", "192.168.1.1/24"))
        item = self.sensorListTable.item(2, 0)
        item.setText(_translate("MainWindow", "12021993"))
        item = self.sensorListTable.item(2, 1)
        item.setText(_translate("MainWindow", "sensor-pens-network-3"))
        item = self.sensorListTable.item(2, 2)
        item.setText(_translate("MainWindow", "PENS"))
        item = self.sensorListTable.item(2, 3)
        item.setText(_translate("MainWindow", "Surabaya, Jawa Timur, Indonesia"))
        item = self.sensorListTable.item(2, 4)
        item.setText(_translate("MainWindow", "192.168.1.2/24"))
        item = self.sensorListTable.item(3, 0)
        item.setText(_translate("MainWindow", "12021994"))
        item = self.sensorListTable.item(3, 1)
        item.setText(_translate("MainWindow", "sensor-pens-network-4"))
        item = self.sensorListTable.item(3, 2)
        item.setText(_translate("MainWindow", "PENS"))
        item = self.sensorListTable.item(3, 3)
        item.setText(_translate("MainWindow", "Surabaya, Jawa Timur, Indonesia"))
        item = self.sensorListTable.item(3, 4)
        item.setText(_translate("MainWindow", "192.168.1.3/24"))
        item = self.sensorListTable.item(4, 0)
        item.setText(_translate("MainWindow", "12021995"))
        item = self.sensorListTable.item(4, 1)
        item.setText(_translate("MainWindow", "sensor-pens-network-5"))
        item = self.sensorListTable.item(4, 2)
        item.setText(_translate("MainWindow", "PENS"))
        item = self.sensorListTable.item(4, 3)
        item.setText(_translate("MainWindow", "Surabaya, Jawa Timur, Indonesia"))
        item = self.sensorListTable.item(4, 4)
        item.setText(_translate("MainWindow", "192.168.1.4/24"))
        self.sensorListTable.setSortingEnabled(__sortingEnabled)
        self.addSensorButton.setText(_translate("MainWindow", "Add Sensor"))
        self.headerLabelMonitorSensor.setText(_translate("MainWindow", "Monitor Sensor"))
        self.tableHeaderMonitorSensor.setText(_translate("MainWindow", "Sensor List"))
        item = self.monitorSensorTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.monitorSensorTable.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.monitorSensorTable.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.monitorSensorTable.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.monitorSensorTable.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.monitorSensorTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Device ID"))
        item = self.monitorSensorTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Device Name"))
        item = self.monitorSensorTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Company"))
        item = self.monitorSensorTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Location"))
        item = self.monitorSensorTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "IP"))
        item = self.monitorSensorTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Up Time"))
        item = self.monitorSensorTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Down Time"))
        __sortingEnabled = self.monitorSensorTable.isSortingEnabled()
        self.monitorSensorTable.setSortingEnabled(False)
        item = self.monitorSensorTable.item(0, 0)
        item.setText(_translate("MainWindow", "12021991"))
        item = self.monitorSensorTable.item(0, 1)
        item.setText(_translate("MainWindow", "sensor-pens-network-1"))
        item = self.monitorSensorTable.item(0, 2)
        item.setText(_translate("MainWindow", "PENS"))
        item = self.monitorSensorTable.item(0, 3)
        item.setText(_translate("MainWindow", "Jawa Timur, Indonesia"))
        item = self.monitorSensorTable.item(0, 4)
        item.setText(_translate("MainWindow", "192.168.1.0/24"))
        item = self.monitorSensorTable.item(0, 5)
        item.setText(_translate("MainWindow", "1 hours 10 minutes"))
        item = self.monitorSensorTable.item(0, 6)
        item.setText(_translate("MainWindow", "0 seconds"))
        item = self.monitorSensorTable.item(1, 0)
        item.setText(_translate("MainWindow", "12021992"))
        item = self.monitorSensorTable.item(1, 1)
        item.setText(_translate("MainWindow", "sensor-pens-network-2"))
        item = self.monitorSensorTable.item(1, 2)
        item.setText(_translate("MainWindow", "PENS"))
        item = self.monitorSensorTable.item(1, 3)
        item.setText(_translate("MainWindow", "Jawa Timur, Indonesia"))
        item = self.monitorSensorTable.item(1, 4)
        item.setText(_translate("MainWindow", "192.168.1.1/24"))
        item = self.monitorSensorTable.item(1, 5)
        item.setText(_translate("MainWindow", "1 hours 10 minutes"))
        item = self.monitorSensorTable.item(1, 6)
        item.setText(_translate("MainWindow", "0 seconds"))
        item = self.monitorSensorTable.item(2, 0)
        item.setText(_translate("MainWindow", "12021993"))
        item = self.monitorSensorTable.item(2, 1)
        item.setText(_translate("MainWindow", "sensor-pens-network-3"))
        item = self.monitorSensorTable.item(2, 2)
        item.setText(_translate("MainWindow", "PENS"))
        item = self.monitorSensorTable.item(2, 3)
        item.setText(_translate("MainWindow", "Jawa Timur, Indonesia"))
        item = self.monitorSensorTable.item(2, 4)
        item.setText(_translate("MainWindow", "192.168.1.2/24"))
        item = self.monitorSensorTable.item(2, 5)
        item.setText(_translate("MainWindow", "1 hours 10 minutes"))
        item = self.monitorSensorTable.item(2, 6)
        item.setText(_translate("MainWindow", "0 seconds"))
        item = self.monitorSensorTable.item(3, 0)
        item.setText(_translate("MainWindow", "12021994"))
        item = self.monitorSensorTable.item(3, 1)
        item.setText(_translate("MainWindow", "sensor-pens-network-4"))
        item = self.monitorSensorTable.item(3, 2)
        item.setText(_translate("MainWindow", "PENS"))
        item = self.monitorSensorTable.item(3, 3)
        item.setText(_translate("MainWindow", "Jawa Timur, Indonesia"))
        item = self.monitorSensorTable.item(3, 4)
        item.setText(_translate("MainWindow", "192.168.1.3/24"))
        item = self.monitorSensorTable.item(3, 5)
        item.setText(_translate("MainWindow", "1 hours 10 minutes"))
        item = self.monitorSensorTable.item(3, 6)
        item.setText(_translate("MainWindow", "0 seconds"))
        item = self.monitorSensorTable.item(4, 0)
        item.setText(_translate("MainWindow", "12021995"))
        item = self.monitorSensorTable.item(4, 1)
        item.setText(_translate("MainWindow", "sensor-pens-network-5"))
        item = self.monitorSensorTable.item(4, 2)
        item.setText(_translate("MainWindow", "PENS"))
        item = self.monitorSensorTable.item(4, 3)
        item.setText(_translate("MainWindow", "Jawa Timur, Indonesia"))
        item = self.monitorSensorTable.item(4, 4)
        item.setText(_translate("MainWindow", "192.168.1.4/24"))
        item = self.monitorSensorTable.item(4, 5)
        item.setText(_translate("MainWindow", "1 hours 10 minutes"))
        item = self.monitorSensorTable.item(4, 6)
        item.setText(_translate("MainWindow", "0 seconds"))
        self.monitorSensorTable.setSortingEnabled(__sortingEnabled)
        self.headerLabelAddSensor.setText(_translate("MainWindow", "Add Sensor"))
        self.protectedSubnetlabel.setText(_translate("MainWindow", "Protected Subnet"))
        self.externalSubnetLabel.setText(_translate("MainWindow", "External Subnet"))
        self.externalSubnetlineEdit.setText(_translate("MainWindow", "default is any"))
        self.mqttTopicLabel.setText(_translate("MainWindow", "MQTT Topic"))
        self.mqttTopiclineEdit.setText(_translate("MainWindow", "default is snoqttv5"))
        self.mqttBrokerLabel.setText(_translate("MainWindow", "Mosquitto (MQTT Broker) IP"))
        self.mqttBrokerPort.setText(_translate("MainWindow", "Mosquitto (MQTT Broker) Port"))
        self.mqttBrokerPortlineEdit.setText(_translate("MainWindow", "default is 1883"))
        self.deviceIDLabel.setText(_translate("MainWindow", "Device ID"))
        self.deviceNameLabel.setText(_translate("MainWindow", "Device Name"))
        self.networkInterfaceLabel.setText(_translate("MainWindow", "Network Interface"))
        self.companyLabel.setText(_translate("MainWindow", "Company"))
        self.ruleChoiceLabel.setText(_translate("MainWindow", "Rule Choice"))
        self.communityradioButton.setText(_translate("MainWindow", "Co&mmunity Rule"))
        self.reisteredradioButton.setText(_translate("MainWindow", "Re&gistered"))


        self.createSensorButton.setText(_translate("MainWindow", "Create Sensor"))
        self.settingheaderLabel.setText(_translate("MainWindow", "Setting"))
        self.nameSettingLabel.setText(_translate("MainWindow", "Name"))
        self.passwordSettingLabel.setText(_translate("MainWindow", "Password"))
        self.submitSettingButton.setText(_translate("MainWindow", "Submit"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuEdit.setTitle(_translate("MainWindow", "E&dit"))
        self.menuFind.setTitle(_translate("MainWindow", "&Find"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.actionNew_Window.setText(_translate("MainWindow", "&New Window"))
        self.actionExit.setText(_translate("MainWindow", "&Exit"))
        self.actionCopy.setText(_translate("MainWindow", "&Copy"))
        self.actionCUt.setText(_translate("MainWindow", "C&ut"))
        self.actionPaste.setText(_translate("MainWindow", "&Paste"))
        self.actionFind_2.setText(_translate("MainWindow", "&Find .."))
        self.actionReplace.setText(_translate("MainWindow", "&Replace"))
    
    def connDB():
        global db_conn
        global db
        db_conn = sqlite3.connect('db_sensor.db')
        db = db_conn.cursor()
    
    def createDataSensor(self):
        #Pilih IP
        list_host = []
        with open("list-host.txt") as f:    
            for line in f:
                line = line.strip()
                list_host.append(line)
        
        self.host = QtWidgets.QLineEdit(self.layoutWidget2)
        self.host.move(130,22)

        host, ok = QInputDialog.getItem(self.layoutWidget2, "Select Available IP", "List of IP", list_host, 0, False)
	
        if ok and host:
            self.host.setText(str(host))
        
        # Input IP kedalam variable hosts
        host = self.host.text()

        # Buat Inventory File untuk Hosts
        hosts_file = open("./ansible/hosts.ini","w+")
        hosts_file.write(host)
        hosts_file.close()


        protectedSubnet = self.protectedSubnetlineEdit.text()
        externalSubnet = self.externalSubnetlineEdit.text()
        mqttTopic = self.mqttTopiclineEdit.text()
        mqttIP = self.mqttBrokerIPlineEdit.text()
        mqttPort = self.mqttBrokerPortlineEdit.text()
        deviceID = self.deviceIDlineEdit.text()
        networkInterface = self.networkInterfacelineEdit.text()
        company = self.companylineEdit.text()
        communityChoice = str(self.communityradioButton.isChecked())
        registeredChoice = str(self.reisteredradioButton.isChecked())

        #Konfigurasi Pilihan User
        communityChoice = str(self.communityradioButton.isChecked())
        registeredChoice = str(self.reisteredradioButton.isChecked())
        if communityChoice == "True":
            ruleChoice = "1"
        
        if registeredChoice == "True":
            ruleChoice = "2"
            self.oinkcode = QtWidgets.QLineEdit(self.layoutWidget2)
            self.oinkcode.move(130,22)

            text, ok = QInputDialog.getText(self.layoutWidget2,'Input oinkcode','Enter your oinkcode :')
            if ok:
                self.oinkcode.setText(str(text))
            
            oinkcode = self.oinkcode.text()
        
        #Tambahkan data ke dalam database 
        db.execute("INSERT INTO tb_sensor_env (protectedSubnet, externalSubnet, mqttTopic, mqttIP, mqttPort, deviceID, networkInterface, company) VALUES(?, ?, ?, ?, ?, ?, ?, ?)",
        (protectedSubnet, externalSubnet, mqttTopic, mqttIP, mqttPort, deviceID, networkInterface, company))

        db_conn.commit()
        
        #Tambah file .env ke /var/tmp/sensor_environment untuk di copy ke remote host
        path_env_checking = os.path.isdir("/var/tmp/sensor_environment")
        output_env_path = str(path_env_checking)
        if output_env_path == "False":
            os.makedirs("/var/tmp/sensor_environment")
        else:
            print("/var/tmp/sensor_environment folder exists")
                
        env_sensor_file = open("/var/tmp/sensor_environment/sensor.env","w+")
        env_sensor_file.write(
            'PROTECTED_SUBNET={0}\nEXTERNAL_SUBNET={1}\nALERT_MQTT_TOPIC={2}\nALERT_MQTT_SERVER={3}\nALERT_MQTT_PORT={4}\nDEVICE_ID={5}\nNETINT={6}\nCOMPANY={7}\n'
            .format(protectedSubnet, externalSubnet, mqttTopic, mqttIP, mqttPort, deviceID, networkInterface, company)
        )
        env_sensor_file.close()

        if ruleChoice == "1":
            Ui_MainWindow.installCommunitySensor()
        else:
            print("Belum ada :p")
    
    def installCommunitySensor():
        os.chdir("/home/taufiq/Documents/DATA/docker-management/ansible")
        os.system("ansible-playbook playbook-install-docker.yml playbook-community-installer.yml -i hosts.ini ")
    
    def readDataSensor():
        db.execute("SELECT * FROM tb_sensor_env")
        data_sensor = db.fetchall()
        for row in data_sensor:
            print(row)

    def copyFileSensor():
        # Copy file .env ke /var/tmp/data_sensor sebagai data sensor pada server
        path_data_sensor_checking = os.path.isdir("/var/tmp/data_sensor")
        output_data_sensor_path = str(path_data_sensor_checking)
        if output_data_sensor_path == "False":
            os.makedirs("/var/tmp/data_sensor")
        else:
            print("/var/tmp/data_sensor folder exists")
        
        src_data_sensor = "/var/tmp/sensor_environment/sensor.env"
        dst_data_sensor = "/var/tmp/data_sensor/sensor-"+deviceID+".env"
        shutil.copy2("/var/tmp/sensor_environment/sensor.env", "/var/tmp/data_sensor/sensor-"+deviceID+".env")
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    Ui_MainWindow.connDB()
    Ui_MainWindow.readDataSensor()
    sys.exit(app.exec_())
