---
- host: all
  become: true
  vars_file: 
  - vars/default.yml

  task:
    - name: Pull Mata Elang Image
      docker_image:
        name: "{{ default_container_image }}"
        tag: mataelang-snort
        source: pull
    
    - name: Create directory for Dockerfile
      file:
        path: /var/tmp/dockerfile
        state: directory
    
    - name: Copy file to remote machine
      copy:
        src: /var/tmp/dockerfile/Dockerfile
        dst: /var/tmp/dockerfile/Dockerfile
    
    - name: Build Image
      docker_image:
        nocache: yes
        build: /var/tmp/dockerfile/
        args: INI_OINKCODE