---
- hosts: all
  become: true
  vars_files:
  - vars/default.yml

  tasks:
  - name: Get Infos on Container
    docker_container_info:
      name: "{{ default_container_name }}"
    register: result
    tags:
      - Get Info Container
  
  - name: Local Copy
    delegate_to: localhost
    copy: 
      content: "{{ result }}"
      dest: "/home/taufiq/Documents/DATA/docker-management/output/info"
  